source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'rackup'
gem 'webrick'
gem 'erubis'
gem 'minitest'
gem 'minitest-reporters'
gem 'rack-test'
gem 'redcarpet'
gem 'bcrypt'

ruby '3.2.2'